services:
  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    volumes:
      - backend_db:/complaints.db
    ports:
      - "8000:8000"
    networks:
      - report_api
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    env_file: .env
    environment:
      - N8N_USER_FOLDER=/data
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    depends_on:
      - backend
    ports:
      - "5678:5678"
    networks:
      - report_api
    volumes:
      - n8n_data:/data
      - ./n8n_init:/n8n_init
    entrypoint: ["/bin/sh", "-c", "/n8n_init/entrypoint.sh"]
    user: "0:0"
    restart: unless-stopped

volumes:
  backend_db:
  n8n_data:

networks:
  report_api:
    driver: bridge
